<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoloadea472668ad449dc63ef26131c10c4939($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'app\\distancecalculator' => '/../App/DistanceCalculator.php',
            'app\\filereader' => '/../App/FileReader.php',
            'app\\findcustomers' => '/../App/FindCustomers.php',
            'app\\userlist' => '/../App/UserList.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoloadea472668ad449dc63ef26131c10c4939', true);
// @codeCoverageIgnoreEnd
